import LoginPanel from './Features/Auth/LoginPanel';
import DiscordRPCService from './Features/DiscordRPC/DiscordRPCService';
import EventService from './Services/Infrastructure/EventService';
import ElementDataService from './Services/Infrastructure/ElementDataService';
import FetchService from './Services/Infrastructure/FetchService';
import InterfaceService from './Services/Infrastructure/InterfaceService';
import NotificationService from './Services/Infrastructure/NotificationService';
import PlayerDataDisplayService from './Features/PlayerDataDisplay/PlayerDataDisplayService';
import CredentialsStorageService from './Services/Utility/CredentialsStorageService';
import Hud from './Features/Hud/Hud';
import Scoreboard from './Features/Scoreboard/Scoreboard';
import KeyboardService from './Services/Utility/KeyboardService';
import PlayerBlipsService from './Services/Utility/PlayerBlipsService';
import AtmFeature from './Features/Atm/AtmFeature';
import HandlingEditorService from './Features/HandlingEditor/HandlingEditorService';
import MarkerService from '@shared-rage/Services/MarkerService';
import InteractionWheelFeature from './Features/InteractionWheel/InteractionWheelFeature';
import VehicleInteractionWheel from './Features/InteractionWheel/VehicleInteractionWheel';
import DrawingService from './Services/Rendering/DrawingService';
import MarkerClientService from './Services/Rendering/MarkerClientService';
import Chat from './Features/Chat/Chat';
import CommandService from './Services/Infrastructure/CommandService';
// import EventServiceTest from './Tests/EventServiceTest';
// import ElementDataServiceTest from './Tests/ElementDataServiceTest';
// import InterfaceServiceTest from './Tests/InterfaceServiceTest';
// import FetchServiceTest from './Tests/FetchServiceTest';
// import NotificationServiceTest from './Tests/NotificationServiceTest';
// import PlayerDataDisplayServiceTest from './Tests/PlayerDataDisplayServiceTest';

(async () => {
	await DiscordRPCService.init();
	await EventService.init();
	await ElementDataService.init();
	await PlayerDataDisplayService.init();
	await CredentialsStorageService.init();
	await KeyboardService.init();
	await InterfaceService.init();
	await PlayerBlipsService.init();
	await FetchService.init();
	await NotificationService.init();
	await HandlingEditorService.init();
	await LoginPanel.init();
	await Hud.init();
	await Scoreboard.init();
	await MarkerService.init();
	await MarkerClientService.init();
	await DrawingService.init();
	await Chat.init();
	await CommandService.init();

	// Features
	await AtmFeature.init();
	await InteractionWheelFeature.init();
	await VehicleInteractionWheel.init();
	// EventServiceTest.init();
	// ElementDataServiceTest.init();
	// InterfaceServiceTest.init();
	// FetchServiceTest.init();
	// NotificationServiceTest.init();
	// PlayerDataDisplayServiceTest.init();
})();
